/*
 * Author: Bruno H. M. Mendanha
 * Id: 20325
 */
package view;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;


public class CreateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CreateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create customer");
        setName("frm_customerView"); // NOI18N
        setResizable(false);

        jLabel1.setText("First name");

        txtName.setToolTipText("");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jButton7.setText("EXIT");
        jButton7.setName("btn_exit"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Creating Customer");

        jLabel2.setText("Last name");

        jLabel3.setText("E-mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addComponent(txtSurname))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       EmployeeActions frm_employeeActions = new EmployeeActions();
            frm_employeeActions.setVisible(true);
            dispose();
//System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        //CREATE CUSTOMER HERE
        
        txtName.getText();
        txtSurname.getText();
        txtEmail.getText();
        String nameCustomer = txtName.getText().toUpperCase();
        String surnameCustomer = txtSurname.getText().toUpperCase();
        String txtEmailCustomer = txtEmail.getText();
        
        String accountNumber;
        String pinNumber;
                
        String iniciaisName;
        iniciaisName = txtName.getText().replaceAll("[^A-Z]+", "");
        iniciaisName =iniciaisName.toLowerCase();
        
        String iniciaisSurname;
        iniciaisSurname = txtSurname.getText().replaceAll("[^A-Z]+", "");
        iniciaisSurname =iniciaisSurname.toLowerCase();
        
        int tamanhoName = nameCustomer.length();
        int tamanhoSurname = surnameCustomer.length();
        int totalLetters= tamanhoName+tamanhoSurname; // The sum of the total of letters in Name and Surname typed
        LocalDateTime agora = LocalDateTime.now(); 
        // Array to get the correspondent index number to name and surname
        String[] arrayName = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","z"};
        int letterName=0;
        for(int i = 0; i < arrayName.length; i++){
            if(arrayName[i].equals(iniciaisName)){
                letterName=i;
            }
        } // end for loop to get the correspondent number to the name
        letterName++;
        
        String[] arraySurname = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","z"};
        int letterSurname=0;
        for(int j = 0; j < arrayName.length; j++){
            if(arrayName[j].equals(iniciaisSurname)){
                letterSurname=j;
            }
        } // end for loop to get the correspondent number to the surname
        letterSurname++;
        
        // ACCOUNT CREATION 
        String accounting;
        accounting=iniciaisName+iniciaisSurname+"-"+totalLetters+"-"+letterName+"-"+letterSurname;
        
        //creating currents accountings   
        String textOnTop = ("Customer: "+nameCustomer+" "+surnameCustomer+" - Account Number: "+iniciaisName+iniciaisSurname+"-"+totalLetters+"-"+letterName+"-"+letterSurname+" Email:"+txtEmailCustomer+" Created "+agora);
        FileWriter current;
	try {
		current = new FileWriter(new File(accounting+"-current.txt"));
		current.write(textOnTop);
		current.close();
	} catch (IOException e) {
		e.printStackTrace();
	} catch (Exception e) {
		e.printStackTrace();
	}
	//creating savings accountings 
        FileWriter savings;
	try {
		savings = new FileWriter(new File(accounting+"-savings.txt"));
		savings.write(textOnTop);
		savings.close();
	} catch (IOException e) {
		e.printStackTrace();
	} catch (Exception e) {
		e.printStackTrace();
	}
        
        //Insert the new customer in a general report
        
        Path getFileCurrent = Paths.get("C:/Java/BankkingApplication/generalreport.txt");
        String txtCustomer = System.lineSeparator()+"Customer: "+nameCustomer+" "+surnameCustomer+" - Account Number: "+iniciaisName+iniciaisSurname+"-"+totalLetters+"-"+letterName+"-"+letterSurname+" Email:"+txtEmailCustomer+" Created "+agora;
                
        try {
            Files.write(getFileCurrent,txtCustomer.getBytes(),StandardOpenOption.APPEND); //Write when the accounting was closed
            
        } catch(Exception erro){
          }
                
        
        
        // Clean screen
        
        
        
        
        
        JOptionPane.showMessageDialog(null,"Customer: "+nameCustomer+" "+surnameCustomer+"\nE-mail: "+txtEmailCustomer+"\nAccount Number: "+iniciaisName+iniciaisSurname+"-"+totalLetters+"-"+letterName+"-"+letterSurname+"\nPIN Number:"+letterName+letterSurname);
        // Clean screen
        txtName.setText(null); //clean the field txtName
        txtSurname.setText(null); //clean the field txtSurname
        txtEmail.setText(null);//clean the field txtEmail

    }//GEN-LAST:event_btnCreateActionPerformed
     
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
