/*
* Author: Bruno H. M. Mendanha
 * Id: 20325
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.ListModel;
/**
 *
 * @author bmend
 */
public class CustomerActions extends javax.swing.JFrame {
    //DefaultListModel<String> listModel;
    private String recebe;
    DefaultListModel modelCurrent = new DefaultListModel();
    DefaultListModel modelSavings = new DefaultListModel();
     
    //WithdrawByCustomer enviaTexto;
    /**
     * Creates new form CustomerActions
     */
    
    public CustomerActions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccounting = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCurrent = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAccounting = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaCurrent = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaSavings = new javax.swing.JList();
        btnSavings = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        lblAccounting.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setText("Accounting");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Access");
        setName("frm_customerActions"); // NOI18N
        setResizable(false);

        btnCurrent.setText("Current");
        btnCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentActionPerformed(evt);
            }
        });

        btnBalance.setText("Balance");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.setToolTipText("");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.setName("btn_exit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel3.setText("Accounting");

        txtAccounting.setEditable(false);
        txtAccounting.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAccounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountingActionPerformed(evt);
            }
        });

        jLabel1.setText("Statement");

        jLabel4.setText("Savings");

        txtAreaCurrent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAreaCurrent.setToolTipText("Statement from CURRENT account");
        jScrollPane3.setViewportView(txtAreaCurrent);
        txtAreaCurrent.getAccessibleContext().setAccessibleParent(txtAreaCurrent);

        txtAreaSavings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAreaSavings.setToolTipText("Statement from SAVINGS account");
        jScrollPane4.setViewportView(txtAreaSavings);

        btnSavings.setText("Savings");
        btnSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavingsActionPerformed(evt);
            }
        });

        jLabel5.setText("Current");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAccounting))
                                    .addComponent(btnDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnSavings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void recebendo (String recebe) {
        txtAccounting.setText(recebe);
        }
  
    private void btnCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentActionPerformed
    // Current      
    modelSavings.clear();
    txtAreaSavings.setModel(modelSavings);
    String nomeCurrent = "C:/Java/BankkingApplication/"+txtAccounting.getText()+"-current.txt";
    try {
      FileReader arqCurrent = new FileReader(nomeCurrent);
      BufferedReader lerArqCurrent = new BufferedReader(arqCurrent);
      String linhaCurrent = lerArqCurrent.readLine(); // Read the first line the variable "linha" get the value of "null" when the process of repetition (while) achieve the end ofd the file
     
     while (linhaCurrent != null) {
        linhaCurrent = lerArqCurrent.readLine(); // Read the second until the last line
         modelCurrent.addElement(linhaCurrent.toString()); 
        txtAreaCurrent.setModel(modelCurrent);
      }
           
      arqCurrent.close();
     
      
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null,"Error opening file" );
    }
        
       
    }//GEN-LAST:event_btnCurrentActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        DepositByCustomer frm_depositbycustomer = new DepositByCustomer();
            frm_depositbycustomer.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        InitialScreen frm_initialScreen = new InitialScreen();
            frm_initialScreen.setVisible(true); 
            dispose();
            
    }//GEN-LAST:event_btnExitActionPerformed

           
    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        //Balance of customer - will be shown in a JOptionPane. (I hope)
        
       JOptionPane.showMessageDialog(null,"            BALANCE"+"\n\nAccount number: "+txtAccounting.getText()+"\n\nCurrent account balance: <empty> " +"\nSavings account balance: <empty>");
       CustomerView frm_customerview = new CustomerView();
            frm_customerview.setVisible(true); 
            dispose();
        
            
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void txtAccountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountingActionPerformed
        
    }//GEN-LAST:event_txtAccountingActionPerformed

    private void btnSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavingsActionPerformed
        // Savings      
    modelCurrent.clear();
    txtAreaCurrent.setModel(modelCurrent);
    String nomeSavings = "C:/Java/BankkingApplication/"+txtAccounting.getText()+"-savings.txt";
    try {
     FileReader arqSavings = new FileReader(nomeSavings);
      BufferedReader lerArqSavings = new BufferedReader(arqSavings);
      String linhaSavings = lerArqSavings.readLine(); // Read the first line the variable "linha" get the value of "null" when the process of repetition (while) achieve the end ofd the file
     
     while (linhaSavings != null) {
        linhaSavings = lerArqSavings.readLine(); // Read the second until the last line
        modelSavings.addElement(linhaSavings.toString()); 
        txtAreaSavings.setModel(modelSavings);
      }
      arqSavings.close();
      
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null,"Error opening file" );
    }
 
    }//GEN-LAST:event_btnSavingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerActions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCurrent;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSavings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAccounting;
    private javax.swing.JTextField txtAccounting;
    private javax.swing.JList txtAreaCurrent;
    private javax.swing.JList txtAreaSavings;
    // End of variables declaration//GEN-END:variables
}
