/*
 * Author: Bruno H. M. Mendanha
 * Id: 20325
 */
package view;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author bmend
 */
public class WithdrawByCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public WithdrawByCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnWithdrawCurrentByCustomer = new javax.swing.JButton();
        btnWithdrawSavingsByCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblAccounting = new javax.swing.JLabel();
        txtAccounting = new javax.swing.JTextField();

        jButton8.setText("Previous Screen");
        jButton8.setName("btn_exit"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Withdraw by customer");
        setName("frm_withdrawByCustomer"); // NOI18N
        setResizable(false);

        jLabel1.setText("Amount");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.setName("btn_exit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Withdraw by Customer");

        btnWithdrawCurrentByCustomer.setForeground(new java.awt.Color(204, 0, 0));
        btnWithdrawCurrentByCustomer.setText("Current");
        btnWithdrawCurrentByCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawCurrentByCustomerActionPerformed(evt);
            }
        });

        btnWithdrawSavingsByCustomer.setForeground(new java.awt.Color(204, 0, 0));
        btnWithdrawSavingsByCustomer.setText("Savings");
        btnWithdrawSavingsByCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawSavingsByCustomerActionPerformed(evt);
            }
        });

        jLabel2.setText("Accounting");

        lblAccounting.setBackground(new java.awt.Color(255, 255, 102));
        lblAccounting.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAccounting.setForeground(new java.awt.Color(255, 255, 51));

        txtAccounting.setEditable(false);
        txtAccounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnWithdrawCurrentByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnWithdrawSavingsByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAccounting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawCurrentByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithdrawSavingsByCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccounting, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        InitialScreen frm_initialScreen = new InitialScreen();
        frm_initialScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed
 public void recebendo (String recebe) {
        txtAccounting.setText(recebe);
               
        }
 
    private void btnWithdrawCurrentByCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawCurrentByCustomerActionPerformed
                                 
        Date agora = new Date();
              
        txtAmount.getText();
        String amountWithdraw = txtAmount.getText();
                
        Path getFileCurrent = Paths.get("C:/Java/BankkingApplication/"+txtAccounting.getText()+"-current.txt");
        String txtCurrent = System.lineSeparator()+agora+"\tWithdraw "+"\t "+"-"+amountWithdraw;
        try {
           Files.write(getFileCurrent,txtCurrent.getBytes(),StandardOpenOption.APPEND); //Write when the accounting was closed
        } catch(Exception erro){
          }
                   
        JOptionPane.showMessageDialog(null,"Your CURRENT account has been debited the amount of: "+amountWithdraw);
        //JOptionPane.showMessageDialog(null,"Account Number: "+conta+" \nWithdraw: "+amountWithdraw);
        
        // Clean screen
        txtAmount.setText(null);//clean the field txtAmount
        txtAccounting.setText(null);//clean the field txtAmount
        InitialScreen frm_initialScreen = new InitialScreen();
        frm_initialScreen.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnWithdrawCurrentByCustomerActionPerformed

    private void btnWithdrawSavingsByCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawSavingsByCustomerActionPerformed
        Date agora = new Date();
        //txtAmount.getText();
        String amountWithdraw = txtAmount.getText();
                
        Path getFileCurrent = Paths.get("C:/Java/BankkingApplication/"+txtAccounting.getText()+"-savings.txt");
        String txtCurrent = System.lineSeparator()+agora+"\tWithdraw "+"\t "+"-"+amountWithdraw;
        try {
           Files.write(getFileCurrent,txtCurrent.getBytes(),StandardOpenOption.APPEND); //Write when the accounting was closed
        } catch(Exception erro){
          }
                   
        JOptionPane.showMessageDialog(null,"Your SAVINGS account has been debited the amount of: "+amountWithdraw);
        //JOptionPane.showMessageDialog(null,"Account Number: "+conta+" \nWithdraw: "+amountWithdraw);
        
        // Clean screen
        txtAmount.setText(null);//clean the field txtAmount
        txtAccounting.setText(null);//clean the field txtAmount
        InitialScreen frm_initialScreen = new InitialScreen();
        frm_initialScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnWithdrawSavingsByCustomerActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         CustomerActions frm_customeractions = new CustomerActions();
            frm_customeractions.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtAccountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawByCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnWithdrawCurrentByCustomer;
    private javax.swing.JButton btnWithdrawSavingsByCustomer;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAccounting;
    private javax.swing.JTextField txtAccounting;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
